### PR TITLE
Mentor notes Content-Type headers bug

### PR DESCRIPTION
**Pull request by ali-7**
modify Content-Type headers to ```object``` instead of ```string``` 

relates to #21

### CODE REVIEW

**Comment by eliasmalik** [comment]
Well spotted @ali-7, thanks! @m4v15 you know the campus schedules better than me, any reason we should hold off merging this/any mentors we should make aware of it?

**Comment by m4v15** [comment]
Yeah, amazing find @ali-7 ! @eliascodes nope, don't think so, presumably @ali-7  is changing this as Gaza are about to deliver it for g6 but k1 and l15 and past this and no one else is preparing for delivery right now.

**Review by m4v15 — APPROVED** [review]

**Comment by ali-7** [comment]
thanks guys :smiley:,
yeah, node week will start next week, here in Gaza.

**Comment by ali-7** [comment]
@RamyAlshurafa  شكرا ع النكشة :P

**Review by eliasmalik — APPROVED** [review]

**Pull request merged**
